# Generated by Django 2.0.6 on 2018-07-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRS_Parse_App', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
